### Gaussian Elimination

In [239]:
import numpy as np
from numpy import linalg

In [240]:
np.set_printoptions(precision=4, suppress=True)
# This will make sure that we can print the matrix in a nice format

In [241]:
a = np.array([[5, 1, 4, 3],
              [1, 6, 3, 0],
              [2, 2, 9, 1],
              [5, 0, 1, 10]],float)

b= np.array([
    [2],
    [1],
    [0],
    [10]
], float)
x= linalg.solve(a,b)
print(a)
print(b)
print(x)

[[ 5.  1.  4.  3.]
 [ 1.  6.  3.  0.]
 [ 2.  2.  9.  1.]
 [ 5.  0.  1. 10.]]
[[ 2.]
 [ 1.]
 [ 0.]
 [10.]]
[[-0.219 ]
 [ 0.2714]
 [-0.1364]
 [ 1.1232]]


In [242]:
from copy import deepcopy

In [243]:
A= deepcopy(a)
A= np.column_stack((A,b)) # augmented b to A
A

array([[ 5.,  1.,  4.,  3.,  2.],
       [ 1.,  6.,  3.,  0.,  1.],
       [ 2.,  2.,  9.,  1.,  0.],
       [ 5.,  0.,  1., 10., 10.]])

In [ ]:
n=len(A)
c= np.zeros_like(a) #creating a zero matrix of the same size as a to store the multipliers
for j in range(n): #column iterator
    for i in range(j+1, n): #row iterator
        c[i,j]= A[i,j]/A[j,j] #multiplier for A[i,j]
        print(c[i,j])
        A[i]= A[i]- c[i,j]*A[j] #update the ith row of A
        print(A)
L= np.identity(n) + c   # Even though we don't need L for the Gaussian elimination, we need it for the LU decomposition

0.2
[[ 5.   1.   4.   3.   2. ]
 [ 0.   5.8  2.2 -0.6  0.6]
 [ 2.   2.   9.   1.   0. ]
 [ 5.   0.   1.  10.  10. ]]
0.4
[[ 5.   1.   4.   3.   2. ]
 [ 0.   5.8  2.2 -0.6  0.6]
 [ 0.   1.6  7.4 -0.2 -0.8]
 [ 5.   0.   1.  10.  10. ]]
1.0
[[ 5.   1.   4.   3.   2. ]
 [ 0.   5.8  2.2 -0.6  0.6]
 [ 0.   1.6  7.4 -0.2 -0.8]
 [ 0.  -1.  -3.   7.   8. ]]
0.27586206896551724
[[ 5.      1.      4.      3.      2.    ]
 [ 0.      5.8     2.2    -0.6     0.6   ]
 [ 0.      0.      6.7931 -0.0345 -0.9655]
 [ 0.     -1.     -3.      7.      8.    ]]
-0.1724137931034483
[[ 5.      1.      4.      3.      2.    ]
 [ 0.      5.8     2.2    -0.6     0.6   ]
 [ 0.      0.      6.7931 -0.0345 -0.9655]
 [ 0.      0.     -2.6207  6.8966  8.1034]]
-0.38578680203045684
[[ 5.      1.      4.      3.      2.    ]
 [ 0.      5.8     2.2    -0.6     0.6   ]
 [ 0.      0.      6.7931 -0.0345 -0.9655]
 [ 0.      0.      0.      6.8832  7.731 ]]


In [ ]:
b_= A[:,-1] #storing the updated b as b_
U= A[:,:len(A)]
print(U,b_)

[[ 5.      1.      4.      3.    ]
 [ 0.      5.8     2.2    -0.6   ]
 [ 0.      0.      6.7931 -0.0345]
 [ 0.      0.      0.      6.8832]] [ 2.      0.6    -0.9655  7.731 ]


##### Now that we have an upper triangular matrix, we can solve for the unknowns using back substitution. The formula for back substitution is:
$$ x_i = \frac{b_i - \begin{pmatrix} U_{i,i+1} \\ U_{i,i+2} \\ \vdots \\ U_{i,n} \end{pmatrix} \,\mathbf{\cdot}\, \begin{pmatrix} x_{i+1} \\ x_{i+2} \\ \vdots \\ x_n \end{pmatrix}}{U_{i,i}}

$$


In [261]:
x=np.zeros_like(b)
for i in reversed(range(n)):
    x[i]= (b_[i] - np.dot(U[i,i+1:],x[i+1:]))/U[i,i] # have to use b_ because b is modified
    #print(x[i])
x

array([-0.219 ,  0.2714, -0.1364,  1.1232])

In [263]:
np.linalg.solve(a,b)

array([-0.219 ,  0.2714, -0.1364,  1.1232])

In [247]:
L

array([[ 1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2   ,  1.    ,  0.    ,  0.    ],
       [ 0.4   ,  0.2759,  1.    ,  0.    ],
       [ 1.    , -0.1724, -0.3858,  1.    ]])

### Solving for x using the LU decomposition

For the LU decomposition method, we first need to decompose the matrix A into two matrices L and U, where L is a lower triangular matrix and U is an upper triangular matrix. 
$$ Ax=b \Rightarrow LUx=b $$
Then, we can solve the system of equations Ax = b by solving the following two systems of equations: 
$$ Ld=b $$
$$ Ux=d $$


checking if the decomposition is correct by multiplying L and U to get A

In [250]:
np.dot(L,U)

array([[ 5.,  1.,  4.,  3.],
       [ 1.,  6.,  3.,  0.],
       [ 2.,  2.,  9.,  1.],
       [ 5.,  0.,  1., 10.]])

In [ ]:
n= len(b)
d= np.zeros_like(b)
for i in range(n):
    d[i]= (b[i]-np.dot((L[i,0:i]),d[0:i]))/L[i,i] # solving for d in Ld=b using forward substitution
x= np.zeros_like(b)
for i in range(n-1,-1,-1):
    x[i]= (d[i]-np.dot(U[i,i+1:],x[i+1:]))/U[i,i] # solving for x in Ux=d using back substitution
print(x)

[[-0.219 ]
 [ 0.2714]
 [-0.1364]
 [ 1.1232]]


In [249]:
linalg.solve(a,b)

array([[-0.219 ],
       [ 0.2714],
       [-0.1364],
       [ 1.1232]])

In [251]:
a

array([[ 5.,  1.,  4.,  3.],
       [ 1.,  6.,  3.,  0.],
       [ 2.,  2.,  9.,  1.],
       [ 5.,  0.,  1., 10.]])

In [252]:
b

array([[ 2.],
       [ 1.],
       [ 0.],
       [10.]])

### Gauss-Jordan

In [253]:
A= np.column_stack((a,b)) #augmented matrix
n=len(A)
c= np.zeros_like(a)
for j in range(n): #column iterator
    for i in range(n): #row iterator
        print(c[i,j])
        if i!=j:
            c[i,j]= A[i,j]/A[j,j]
            A[i]= A[i]- c[i,j]*A[j] #Updating the ith row using the jth row as pivot
            print(A)
    A[j]/=A[j,j] #Normalizing each pivot row after the elimination
    print(A)

0.0
0.0
[[ 5.   1.   4.   3.   2. ]
 [ 0.   5.8  2.2 -0.6  0.6]
 [ 2.   2.   9.   1.   0. ]
 [ 5.   0.   1.  10.  10. ]]
0.0
[[ 5.   1.   4.   3.   2. ]
 [ 0.   5.8  2.2 -0.6  0.6]
 [ 0.   1.6  7.4 -0.2 -0.8]
 [ 5.   0.   1.  10.  10. ]]
0.0
[[ 5.   1.   4.   3.   2. ]
 [ 0.   5.8  2.2 -0.6  0.6]
 [ 0.   1.6  7.4 -0.2 -0.8]
 [ 0.  -1.  -3.   7.   8. ]]
[[ 1.   0.2  0.8  0.6  0.4]
 [ 0.   5.8  2.2 -0.6  0.6]
 [ 0.   1.6  7.4 -0.2 -0.8]
 [ 0.  -1.  -3.   7.   8. ]]
0.0
[[ 1.      0.      0.7241  0.6207  0.3793]
 [ 0.      5.8     2.2    -0.6     0.6   ]
 [ 0.      1.6     7.4    -0.2    -0.8   ]
 [ 0.     -1.     -3.      7.      8.    ]]
0.0
0.0
[[ 1.      0.      0.7241  0.6207  0.3793]
 [ 0.      5.8     2.2    -0.6     0.6   ]
 [ 0.      0.      6.7931 -0.0345 -0.9655]
 [ 0.     -1.     -3.      7.      8.    ]]
0.0
[[ 1.      0.      0.7241  0.6207  0.3793]
 [ 0.      5.8     2.2    -0.6     0.6   ]
 [ 0.      0.      6.7931 -0.0345 -0.9655]
 [ 0.      0.     -2.6207  6.8966  8.1034

Since what we get in place of the original matrix is an identity matrix, our solution is the last column of the augmented matrix.

In [264]:
x= A[:,-1]
x

array([-0.219 ,  0.2714, -0.1364,  1.1232])

In [254]:
linalg.solve(a,b)

array([[-0.219 ],
       [ 0.2714],
       [-0.1364],
       [ 1.1232]])

### Gauss- Seidel

The Gauss-Seidel method is a numerical method used to solve a system of linear equations. It is an iterative method that starts with an initial guess for the solution and then uses the current guess to generate a new guess. The process is repeated until the difference between the current guess and the previous guess is less than a specified tolerance. The x values are first initialized to 0. The x values are then updated using the follwing iterative rule:
$$x_i = \frac{b_i - \begin{pmatrix} a_{i,1} \\ a_{i,2} \\ \vdots \\ \mathbf{\cancel{a_{i,i}}} \\ \vdots \\ a_{i,n} \end{pmatrix} \,\mathbf{\cdot}\, \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ \mathbf{\cancel{x_i}} \\ \vdots \\ x_n \end{pmatrix}}{a_{i,i}}
$$
The barred values are the ones that are not used in the calculation. 

In [256]:
print(a)
print(x)

[[ 5.  1.  4.  3.]
 [ 1.  6.  3.  0.]
 [ 2.  2.  9.  1.]
 [ 5.  0.  1. 10.]]
[[-0.219 ]
 [ 0.2714]
 [-0.1364]
 [ 1.1232]]


In [269]:
def GaussSeidel(a,b,e=0.0001,max_iter=100):  
    # Convert b to 1D array
    b = b.flatten()
    # Initialize x to zero
    x = np.zeros_like(b)
    n = len(x)
    for k in range(max_iter): # 10 iterations
        x_old= x.copy()
        for i in range(n):
            # simpler way to  do this is to use numpy.delete without using slicing to make the code more concise
            # np.delete(a[i],i) means delete the i-th element of a[i]
            x[i] = (b[i] - np.dot(np.delete(a[i], i), np.delete(x, i)))/a[i][i]
            print(x)
        error= np.linalg.norm(x-x_old,ord=np.inf) #calculate the difference between the old and new values
        if error<e:
            break
    print(x)
    return x


In [270]:
GaussSeidel(a,b)

[0.4 0.  0.  0. ]
[0.4 0.1 0.  0. ]
[ 0.4     0.1    -0.1111  0.    ]
[ 0.4     0.1    -0.1111  0.8111]
[-0.0178  0.1    -0.1111  0.8111]
[-0.0178  0.2252 -0.1111  0.8111]
[-0.0178  0.2252 -0.1362  0.8111]
[-0.0178  0.2252 -0.1362  1.0225]
[-0.1496  0.2252 -0.1362  1.0225]
[-0.1496  0.2597 -0.1362  1.0225]
[-0.1496  0.2597 -0.1381  1.0225]
[-0.1496  0.2597 -0.1381  1.0886]
[-0.1946  0.2597 -0.1381  1.0886]
[-0.1946  0.2681 -0.1381  1.0886]
[-0.1946  0.2681 -0.1373  1.0886]
[-0.1946  0.2681 -0.1373  1.111 ]
[-0.2104  0.2681 -0.1373  1.111 ]
[-0.2104  0.2704 -0.1373  1.111 ]
[-0.2104  0.2704 -0.1368  1.111 ]
[-0.2104  0.2704 -0.1368  1.1189]
[-0.216   0.2704 -0.1368  1.1189]
[-0.216   0.2711 -0.1368  1.1189]
[-0.216   0.2711 -0.1366  1.1189]
[-0.216   0.2711 -0.1366  1.1217]
[-0.218   0.2711 -0.1366  1.1217]
[-0.218   0.2713 -0.1366  1.1217]
[-0.218   0.2713 -0.1365  1.1217]
[-0.218   0.2713 -0.1365  1.1226]
[-0.2186  0.2713 -0.1365  1.1226]
[-0.2186  0.2713 -0.1365  1.1226]
[-0.2186  0.

array([-0.219 ,  0.2714, -0.1364,  1.1231])

In [258]:
x

array([-0.219 ,  0.2714, -0.1364,  1.1232])